ANIMEQUOTE = (
    "❝There are days when nothing goes right. There are days when you stumble and fall. There are days when you just want to cry. To cry a lot. To sleep a lot. Or even eat a lot. It’s alright, as long as you pick yourself up again.❞ – Yuki Takeya (Gakkougurashi!)",
    "❝Excuse me but are you by any chance the oddball in your family?❞– Ash Ketchum",
    "❝The world isn't perfect. But it's there for us, doing the best it can....that's what makes it so damn beautiful.❞ ~ Roy Mustang (Full Metal Alchemist)",
    "❝To know sorrow is not terrifying. What is terrifying is to know you can't go back to happiness you could have.❞ ~ Matsumoto Rangiku (Bleach)",
    "❝Those who stand at the top determine what's wrong and what's right! This very place is neutral ground! Justice will prevail, you say? But of course it will! Whoever wins this war becomes justice!❞ ~ Don Quixote Doflamingo (One Piece)",
    "❝Living has it own challenges. I’ll give you just one piece of advice. Don’t quit. Yes, when you die, you die. But if you give up, you’re definitely going to die. That, I am sure of.❞ – Brittany (Hai to Gensou no Grimgar)",
    "❝All I Can Do Is Work Hard! That’s The Story Of My Life!❞ - Tanjiro Kamado (Demon Slayer: Kimetsu no yaiba)",
    "❝You can’t sit around envying other people’s worlds. You have to go tout and change your own.❞ – Shinichi Chiaki (Nodame Cantabile)",
    "❝We cannot go back to the past, no matter how hard we try. No matter how wonderful it was. The past is nothing but the past.❞ – Eikichi Onizuka (Great Teacher Onizuka:GTO)",
    "❝It’s not like something is going to happen because I believe in it. Sometimes you end up worse off because you believed in something too much. There are times it’s tough to believe in something.❞ – Eureka (Eureka Seven)",
    "❝I don’t think I’ll learn anything if I don’t try to do something about it on my own.❞ – Chizuru Hishiro (ReLIFE)",
    "❝A dropout will beat a genius through hard work.❞ – Rock Lee (Naruto)",
    "❝You guys sure are a worthless bunch. If you wanna wallow in your tears, save it for after you’ve done everything you can.❞ – Seiya Kanie (Amagi Brilliant Park)",
    "❝Smile. Not for anyone else, but for yourself. Show yourself your own smile. You’ll feel better then.❞ – Rintaro Tatewaki (Magic-Kyun! Renaissance)",
    "❝It may be hard right now, but you must silence those thoughts. Stop counting only those things that you have lost. What is gone, is gone.❞ – Jinbei (One Piece)",
    "❝Remember this… no matter where you go, the strength of your mind and spirit is the most powerful magic of all.❞ – Princess Emeraude (Magic Knight Rayearth)",
    "❝I haven’t relied on luck since the moment I was born. Everything has been the result of my choices.❞ – Kagura Mikazuchi (Fairy Tail)",
    "❝If praying does not work, and words are ineffective, what’s left is to fight.❞ – Meme Oshino (Bakemonogatari)",
    "❝Whether a fish lives in a clear stream or a water ditch, so long as it continues swimming forward, it will grow up beautifully.❞ – Koro-sensei (Assassination Classroom)",
    "❝If you feel yourself hitting up against your limit, remember for what cause you clench your fists! Remember why you started down this path, and let that memory carry you beyond your limit.❞ – All Might (My Hero Academia)",
    "❝Fear is not evil. It tells you what your weakness is. And once you know your weakness, you can become stronger, as well as kinder.❞ – Gildarts Clive (Fairy Tail)",
    "❝How can you move forward if you keep regretting the past?❞ – Edward Elric (Fullmetal Alchemist)"
    "❝I envy you because you can easily forget your troubles and sadness.❞ – Kanzaki Urumi (Great Teacher Onizuka:GTO)",
    "❝The only thing we're allowed to believe is that we won't regret the choice we made.❞ – Levi Ackerman (Attack On Titan: Shinkeji No Kyojin)",
    "❝Maybe there’s only a dark road up ahead. But you still have to believe and keep going. Believe that the stars will light your path, even a little bit. Come on, let’s go on a journey!❞ – Kaori Miyazono (Shigatsu Wa Kimi No Uso)",
    "❝Although I’m weak and full of flaws, I will never stop moving forward. No matter who I am, no one other than myself will create my own existence. No matter what others may think or feel, I will still move forward as myself.❞ – Oz Vessalius (Pandora Hearts)",
    "❝In this world, there’s no such thing as ‘failure’ in the first place. The one who knows the ‘ways to win’ more than anyone is also the one who’s experienced the most ‘mistakes’. In other words… You could say ‘failure’ is equal to ‘success’… Couldn’t you?❞ – Toriko (Toriko)",
    "❝If you can’t do something, then don’t. Focus on what you can do.❞ – Shiroe (Log Horizon)",
    "❝Life is like a tube of toothpaste. When you’ve used all the toothpaste down to the last squeeze, that’s when you’ve really lived. Live with all your might, and struggle as long as you have life.❞ – Mion Sonozaki (Higurashi no Naku Koro ni)",
    "❝I won’t be defeated because I know how awful it feels to lose after doing my very best!❞ – Sho Kazamatsuri (Whistle!)",
    "❝Stop pouting! You learned something valuable. Remember the lesson, not the disappointment.❞ – Holo (Spice & Wolf)",
    "❝I don’t have time to worry if it’s right or wrong, you can’t hope for a horror story with a happy ending.❞ – Eren Jaeger (Attack On Titan: Shinkeji No Kyojin)",
    "❝The ones who accomplish something are the fools who keep pressing onward. The ones who accomplish nothing are the wise who cease advancing.❞ – Celica Arfonia (Rokudenashi Majutsu Koushi to Akashic Records)",
    "❝Just walk the path you believe in. And don’t forget, you’re the main character of your own life story!❞ – Glenn Radars (Rokudenashi Majutsu Koushi to Akashic Records)",
    "❝The only one who can decide your worth.. is you. If you want to earn something, you need to reach out for it. Pro-athletes give up their teenage years to train. Business owners put up collateral to borrow money. That’s how it always works. To make your ambitions come true, you have to take risks. The larger the ambition the greater the risk. That might involve time or enough work to affect your lifespan… So make your choice. Live in peace as a wannabe or risk losing it all to reach the very top. You’re the one who needs to decide.❞ – Jabami Yumeko (Kakegurui)",
    "❝The lifespan of a human is certainly way too short. That’s why you’ve got to make the most of it and live your life to the fullest.❞ – Leone (Akame Ga Kill!)",
    "❝Enjoy your life today. Yesterday is gone, and the tomorrow might never come.❞ – Takeshi Yamamoto (Katekyo Hitman Reborn!)",
    "❝A road is something that you make yourself.❞ – Jotaro Kujo (JoJo’s Bizarre Adventure)",
    "❝No matter what you’re doing, the most essential thing is to not give up. Fail as many times as it takes. Keep trying persistantly untill you can call yourself ‘avarage’. If you can collect a nice group of avarage-level skills, that’s already above-avarage. You’ve created your own sort of ‘talent’.❞ – Yuuji Kazami",
    "❝People’s lives don’t end when they die, it ends when they lose faith.❞ – Itachi Uchiha (Naruto)",
    "❝If you don’t like your destiny, don’t accept it.❞ – Naruto Uzumaki (Naruto)",
    "❝You know, when I was in high school, I was a troublemaker. I hardly went to school. Before I knew it, I was expelled. When I couldn’t go anymore was when I first realized, that school was a great thing. There’s a lot of friends and lots of fun things. When I got this old, I wanted even more to go to school. That’s why I became a teacher. Because, if I become a teacher, I could stay in school until I die, right? That’s why I’m really happy now. I want you to be like that too. I want you to like school. Once it’s over, it’s too late.❞ – Eikichi Onizuka (Great Teacher Onizuka:GTO)",
    "❝When you give up, that’s when the game ends.”❞ – Mitsuyoshi Anzai (Slam Dunk)",
    "❝All we can do is live until the day we die. Control what we can…and fly free.❞ – Deneil Young (Uchuu Kyoudai or Space Brothers)",
    "❝Forgetting is like a wound. The wound may heal, but it has already left a scar.❞ – Monkey D. Luffy (One Piece)",
    "❝Giving up kills people. When people reject giving up… they finally win the right to transcend humanity.❞ – Alucard (Hellsing)",
    "❝If you don’t share someone’s pain, you can never understand them.❞ – Nagato (Naruto)",
    "❝Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.❞ – Himura Kenshin (Rurouni Kenshin)",
    "❝We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today!❞ – Natsu Dragneel (Fairy Tail)",
    "❝Being weak is nothing to be ashamed of… Staying weak is !!❞ – Fuegoleon Vermillion (Black Clover)",
    "❝Reject common sense to make the impossible possible.❞ – Simon (Tengen Toppa Gurren Lagann)",
    "❝This is just my opinion but… I feel that those who recognize one right way will never go beyond and reach truly amazing things. But more importantly… the journey is no fun if you know where you are going.❞ -Soma Yukihira (Food Wars: Shokugeki No Soma)",
    "❝Being alone is better than being with the wrong person.❞ – L (Death Note)",
    "❝If you really want to be strong… Stop caring about what your surrounding thinks of you!❞ – Saitama (One Punch Man)",
    "❝Who decides limits? And based on what? You said you worked hard? Well, maybe you need to work a little harder. Is that really the limit of your strength? Could the you of tomorrow beat you today? Instead of giving in, move forward.❞ – Saitama (One Punch Man)",
    "❝A person grows up when he’s able to overcome hardships. Protection is important, but there are some things that a person must learn on his own.❞ – Jiraiya (Naruto)",
    "❝Hard work is worthless for those that don’t believe in themselves.❞ – Naruto Uzumaki (Naruto)",
    "❝Mistakes are not shackles that halt one from stepping forward. Rather, they are that which sustain and grow one’s heart.❞ – Mavis Vermillion (Fairy Tail)",
    "❝A place where someone still thinks about you is a place you can call home.❞ – Jiraiya (Naruto)",
    "❝For you, she maybe just someone among the 400 students, but for a student, there’s only one teacher for them.❞ – Eikichi Onizuka (Great Teacher Onizuka:GTO)",
    "❝There’s no gender distinction among the bad.❞ – Eikichi Onizuka (Great Teacher Onizuka:GTO)",
    "❝Life comes at a cost. Wouldn’t it be arrogant to die before you’ve repaid that debt?❞ – Yuuji Kazami (The Fruit of Grisaia / Gurizaia no Kajitsu)",
    "❝Vision is not what your eyes see, but an image that your brain comprehends.❞ – Touko Aozaki (The Garden of Sinners / Kara no Kyōkai)",
    "❝Hatred and Sorrow are power. They are yours to control. All you have to do is to turn them into strength and use that strength to move forward.❞ – Sebastian Michaelis (Black Butler / Kuroshitsuji)",
    "❝It’s not always possible to do what we want to do, but it’s important to believe in something before you actually do it.❞ – Might Guy (Naruto)",
    "❝Don’t beg for things. Do it yourself, or else you won’t get anything.❞ – Renton Thurston (Eureka Seven)",
    "❝I will fulfill my duty! I won't let anyone here die!❞ - Kyojuro Rengoku (Demon Slayer:Kimetsu No Yaiba)",
    "❝The trick to being a good chef, is the right woman. A woman who will make you a better man. Better at cooking. Better at everything.❞ – Joichiro Saiba (Food Wars: Shokugeki No Soma)",
    "❝Life and death are like light and shadow. They’re both always there. But people don’t like thinking about death, so subconsciously, they always look away from it.❞ – Yato (Noragami)",
    "❝Moving on doesn’t mean you forget about things. It just means you have to accept what’s happened and continue living.❞ – Erza Scarlet (Fairy Tail)",
    "❝If you keep on hiding your true feelings, who is going to be happy? If you are sad, you should say it out loud!❞ – Haruhi Fujioka (Ouran High School Host Club)",
    "❝You were always a diligent girl who would steadily learn and master all sorts of techniques… but the other side of that is, you were merely recreating exactly what you have been taught. You never even stopped to consider the true nature of things. Will people enjoy the soba that I will make? Will the flavors really be conveyed to the people who eat it? You had no regard for such things, that is why you lost to Soma before the match even began.❞ – Satoshi Isshiki (Food Wars: Shokugeki No Soma)",
    "❝You can die anytime, but living takes true courage.❞ – Himura Kenshin (Rurouni Kenshin)",
    "❝You can't judge a book by it's cover but boxes are a whole nother story❞ – Eikichi Onizuka (Great Teacher Onizuka:GTO)",
    "❝Every journey begins with a single step. We just have to have patience.❞ – Milly Thompson (Trigun)",
    "❝A brat who is afraid to be hurt isn’t qualified to love someone.❞ – Eikichi Onizuka (Great Teacher Onizuka:GTO)",
    "❝If nobody cares to accept you and wants you in this world, accept yourself and you will see that you don’t need them and their selfish ideas.❞ – Alibaba Saluja (Universal Warriors)",
    "❝Don’t be upset because of what you can’t do. Do what you do best, live as carefree and optimistically as you can, because some people aren’t able to do that.❞ – Keima Katsuragi (The World God Only Knows)",
    "❝If you begin to regret, you’ll dull your future decisions and let others make your choices for you. All that’s left for you then is to die. Nobody can foretell the outcome. Each decision you make holds meaning only by affecting your next decision.❞ – Erwin Smith (Attack on Titan: Shinjeki No Kyojin)",
    "❝Everything has a beginning and an end. Life is just a cycle of starts and stops. There are ends we don’t desire, but they’re inevitable, we have to face them. It’s what being human is all about.❞ – Jet Black (Cowboy Bebop)",
    "❝Anything can happen. No one ever thinks it will until it does. What will happen, happens. That’s how the world is. The most important thing is to not let the tragedy defeat you. To believe that you can get through it.❞ – Kyousuke Natsume (Little Busters!)",
    "❝You’ll only realize that you truly love someone if they already caused you enormous pain. Your enemies can never hurt you the way your loved ones can. It’s the people close to your heart that can give you the most piercing wound. Love is a double-edged sword, it can heal the wound faster or it can sink the blade even deeper.❞ – Himura Kenshin (Rurouni Kenshin)",
    "❝It is at the moment of death that humanity has value.❞ – Archer (Fate Series)",
    "❝A lesson without pain is meaningless. That’s because no one can gain without sacrificing something. But by enduring that pain and overcoming it, he shall obtain a powerful, unmatched heart.❞ – Edward Elric (Fullmetal Alchemist: Brotherhood)",
    "❝Feel The Rage. The Powerful, Pure Rage Of Not Being Able To Forgive Will Become Your Unswerving Drive To Take Action.❞ - Giyuu Tomioka (Demon Slayer: Kimetsu No Yaiba)",
    "❝No Matter How Many People You May Lose, You Have No Choice But To Go On Living - No Matter How Devastating The Blows, Maybe.❞ - Tanjiro Kamado (Demon Slayer: Kimetsu No Yaiba)",
    "❝It's Not About Going First. It's About The Overall Flow.❞ - Inosuke Harshibra (Demon Slayer: Kimetsu No Yaiba)",
    "❝Even if all the confidence and pride you’ve built over the years is blown to pieces by a major failure, even if you’ve had a soul-crushing experience, you still have to open the shop the next day. That’s who chefs are.❞ – Soma Yukihira (Shokugeki no Soma: Ni no Sara)",
    "❝Everyone has their own talents, and strong wills that won’t lose to anyone else.❞ – Sakamoto Yuuji (Baka to Test to Shoukanjuu)",
    "❝You are too young to worry about failure. In a pinch, just muddle through. The outcome won’t change, so that’s best.❞ – Bang (One Punch Man)",
    "❝Do exactly as you like. That is the true meaning of pleasure. Pleasure leads to joy and joy leads to happiness. Your path is now clear, Kirei. So clear there is no longer any need to hesitate.❞ – Gilgamesh (Fate/Zero)",
    "❝As long as we are under the same sky, we shouldn’t be sad when we part ways.❞ – Wolfgang Grimmer (Monster)",
    "❝If something is possible, carry on as planned. Even if it isn’t possible, do it anyway.❞ – Karasuma Tadaomi (Assassination Classroom)",
    "❝Just ’cause you’re a girl, it doesn’t mean you have to wait for a prince to come along on a white horse. You can go out and find Prince Charming yourself. It is up to you to find the right boy.❞ – Sailor Chibi Moon (Sailor Moon)",
    "❝If you want to grow, just look above you. There are plenty of people perfect to serve as fodder for your growth.❞ – Kojiro Shinomiya (Food Wars: Shokugeki No Soma)",
    "❝If you have the guts to not give up, you can be anything you want to be. We’re living creature that don’t have wings, but still went to the moon.❞ – Kurogane Ryouma (Rakudai Kishi no Cavalry)",
    "❝Power is not the only connection you can have. This world is filled with much warmer things.❞ – Minerva Orland (Fairy Tail)",
    "❝There are some flowers you only see when you take detours.❞ – Tanaka Saeko (Haikyuu!!)",
    "❝I thought that when I grew up, I could reach more and more. The delicious looking fruit beckoning from the highest branch.The beautiful shell hidden in the sand. If I could only stretch out my hand a little more…. But…. As everyone passes through the junctures of their life, they no longer stretch their hand to the sky, or crouch to the earth. Embarrassed, they ignore what they’d desired for so long. Will you reach out and grab me, grown up as I am?❞ – Kou Ichinomiya (Arakawa Under the Bridge)",
    "❝I’ll use my flames for a better purpose!❞ – Rin Okumura (Ao no Exorcist)",
    "❝Examined from another angle, your faults and weaknesses can be weapons.❞ – Nagisa Shiota (Assassination Classroom 2nd Season)",
    "❝I don’t care if no one likes me. I wasn’t created in this world to entertain everyone.❞ – Oreki Houtarou (Hyouka)",
    "❝You’ve really got to hold on to what’s important to you.❞ – Kazuya Kujo (Gosick)",
    "❝The future is always blank. Only your willpower can leave footsteps there.❞ – Satoru Fujinuma (Boku dake ga Inai Machi)",
    "❝If you’re ever lost in the darkness, follow the compass in your heart.❞ – Kayo Senju (Black Bullet)",
    "❝At times, I feel as though the whole world is gray, as though time is standing still. But time never stops. It moves forward endlessly, as surely as bodies buried in the ground will one day become white bones. Listen, it’s always you who stops time. If you stop in fear of the future – you gain nothing, and nothing begins. You spend your life as though already dead. Whether you wish it to or not – time never stops. That’s why there is nothing more interesting than this world. Don’t be too negative. You haven’t become ashes just yet. You have your flesh and blood, and your bones are supporting you.❞ – Sakurako Kujo (Beautiful Bones: Sakurako’s Investigation)",
    "❝When I want to do something, I do it, regardless of the rest of the world. When I don’t, I don’t, and that’s that.❞ – Femt (Kekkai Sensen)",
    "❝If you want to be strong, smile! He who can smile, even when he’s so sad that he wants to die, when it’s so painful that he wants to give it all up and run away, is the one who becomes strong.❞ (Rokka no Yuusha)",
    "❝If you trust in the possibilities within and try with all your might, the path will show itself to you!❞ – Cardeas Vist (Mobile Suit Gundam UC)",
    "❝If You Can Do One Thing, Hone It To Perfection. Hone It To The Utmost Limit.❞ – Jigoro Agatsuma (Demon Slayer: Kimetsu No Yaiba)",
    "❝A journey of a thousand miles begins with a single step. Even though each step is small, you never know if you’ll end up achieving your major goal.❞ – Ensei Rou (The Story of Saiunkoku)",
    "❝Even if I found happiness, my weakness can’t be discarded. But, even so, I’m sure that we took the right path to move forward.❞ – Adolf Reinhardt (Terra Formars)",
    "❝Don’t Ever Give Up. Even If It’s Painful, Even If It’s Agonizing, Don’t Try To Take The Easy Way Out.❞ – Zenitsu Agatsuma (Demon Slayer: Kimetsu No Yaiba)",
    "❝The end result is important. But what’s truly important… is the journey to get there.❞ – Hikari Hanazono (Special A)",
    "❝God would never put us through all this suffering if he didn’t think we could bear it.❞ – Konno Yuuki (Sword Art Online II)",
    "❝Whether it’s disappointing or not depends on the person. Things like uneasiness or indecision are in everyone’s lives. What’s important is to appreciate and grow from every kind of result. If you can grow from them, you can understand that all events are for the purpose of growing and you can appreciate them.❞ – Coco (Toriko)",
    "❝If you want to run from your past, fine. But whatever you do, don’t run away from your present or worse, your future.❞ – Kyohei Kadota (Durarara!!)",
    "❝The same melody repeats itself as the song grows richer and more beautiful. Wouldn’t it be wonderful if we could live seemingly constant lives while experiencing changes bit by bit?❞ – Sayuri Kurata (Kanon)",
    "❝I never thought about winning making me cool, or losing making me uncool. But you’re right. If anything… Giving up before you even try is kind of uncool. That’s why I want to be someone who’ll fight as many times as it takes, and never give up. That’s got to be way more cooler.❞ – Tachibana Hotaru (Aoharu x Kikanjuu)",
    "❝Stand tall and be proud. No matter how weak or unworthy you feel keep your heart burning, grit your teeth and move forward. If you just curl up in a ball and hide, time will pass you by. It won't stop for you while you wallow in your grief.❞ - Kyojuro Rengoku (Demon Slayer:Kimetsu No Yaiba)",
    "❝You think you can just escape? Walk out of this world like it’s some bad movie? It’s too easy to make like a bird. To flap your wings as you chicken out after causing all these problems. The tough part’s walking. Taking what comes along and walking right through it. That’s what real people do.❞ – Eikichi Onizuka (Great Teacher Onizuka)",
)
