RUN_STRINGS = (
    "Now you see me, now you don't."
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

GIFS = [
    'CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE',
    'CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE',
    'CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA'
]

SLAP_SAITAMA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!"
    ])

SLAP_TEMPLATES = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  #No game no life reference
    "Shut up {user2}, you are just {user2}.",  #No game no life reference
    "{user1} hits {user2} with Aka si anse!",  #No game no life reference
    "@NeoTheKitty scratches {user2}",  #Pixels pet cat - @NeoTheKitty 
    "Majin buu ate {user2}",  #Dbz
    "Goblin slayer slays {user2}",  #Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAx0CVIxhUQABBPBqX6vdaOZAh-oEMkhr-YWiZRaT4d0AAmUCAALTGoxSFYSCjyjQw4ceBA",
    "CgACAgQAAx0CVIxhUQABBPBrX6vda2H3ndz9bItHho7hHPYhgzcAAmACAAL1G4xSe4c88D6r_0QeBA",
    "CgACAgQAAx0CVIxhUQABBPBsX6vdcChswNvhzn9SX2n7dWWdbIMAAi8CAAIThY1S7EzxeOq7lnMeBA",
    "CgACAgQAAx0CVIxhUQABBPBtX6vdctBhMfHafbAXZ0KTKGI3sk4AAkcCAAI68I1SGSVAPZxn8FMeBA",
    "CgACAgQAAx0CVIxhUQABBPBuX6vddzBrAW7RMLOJTPe7L6GbhLUAAnoCAAJ2D9VQ903bbGnfonseBA",
    "CgACAgQAAx0CVIxhUQABBPBvX6vdeSdSOA44JIHATc8yoA9hB9AAAk8CAAIpO_1SjyLzlc6U2jMeBA",
    "CgACAgQAAx0CVIxhUQABBPBwX6vdfSzhkHq4zVSRaehP685OC6kAAh4CAAJPcjxQK0-BFUKPS3keBA",
    "CgACAgQAAx0CVIxhUQABBPBxX6vdfu5iI046FwYQ8-eTX1IUWcwAAhUCAAJ5VtVSMnu7A64nFyoeBA",
    "CgACAgQAAx0CVIxhUQABBPByX6vdf0w3SnsIvD2lE0QaDKv15LMAAiMCAAI3KIxSKBWsoGMyVdMeBA",
    "CgACAgQAAx0CVIxhUQABBPBzX6vdgPZ3xUB5kCUJ5rOCeiVlD9cAAiQCAALHb9RS5D9chc10JU0eBA",
    "CgACAgQAAx0CVIxhUQABBPB0X6vdgeeWISo24Dlbc3x3GHOtlmcAAjICAAJi3v1SKalLvmlnxSYeBA",
    "CgACAgQAAx0CVIxhUQABBPB1X6vdg3MKn9G-V18Ql4rChw6JNecAAjMCAAJ-4oxS042ErKcOHU8eBA",
    "CgACAgQAAx0CVIxhUQABBPB2X6vdhKM-uWFDz7TvebNt7hpfm78AAlwCAAJH8Y1SW3_ZGMhg_UIeBA",
    "CgACAgQAAx0CVIxhUQABBPB3X6vdhr807S_TGtiR7E62DPd1KfsAAiICAAKWSNVSe0DCWq2bgpYeBA",
    "CgACAgUAAx0CVIxhUQABBPB-X6vd0-7kD95VOWaMyGP5V7864p8AAosBAAKlEGFVdjgfsh20ZyceBA")

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ")


DYK_TEMPLATES = (
	"〔ANIME IS HUGE, ESPECIALLY IN JAPAN.〕 \n\n｢According to a 2004 document from the Japan External Trade Organization, anime films and television shows account for 60% of the world’s animation-based entertainment. Almost 40 schools in Japan have declared anime as an individual subject on its own. Anime voice acting is also huge, as Japan has around 130 voice-acting schools. In Japan, more paper is used to print manga than toilet paper.｣", #Facts from https://newslanded.com/2020/07/03/12-shocking-facts-about-anime-you-need-to-know/
	"〔THE HIGHEST-GROSSING ANIME FILM OF ALL TIME IS KIMI NO NA WA (YOUR NAME).〕\n\n｢The critical and commercial success of Makoto Shinkai’s Your Name can’t be understated. This film brought in more than $355 million worldwide. \nA unique and fictional storyline really makes this anime movie stand out from the others. Amazingly, most of the places shown in this anime are real! Here is one of them!｣",
	"〔ANIME IS NOT THE SAME AS “CARTOON,” CONTRARY TO POPULAR BELIEF.〕\n\n｢With complicated stories and in-depth character development, anime avoids the cartoon label and makes claims on being a higher art form.｣",
	"〔THE LONGEST-RUNNING ANIME HAS OVER 7,500 EPISODES.〕\n\n｢Sazae-san has over 7500 episodes, but each is only about six minutes long. Manga Nippon Mukashibanashi has over 1400 episodes of about 25 minutes each.｣",
	"〔ONE ANIME CHARACTER HAS 22 DIFFERENT VOICE ACTRESSES.〕\n\n｢Eucliwood Hellscyth from Is This a Zombie? has 22 voice actresses in 22 episodes. The character herself is mostly mute. However, all her speaking lines are all imagined by the protagonist, resulting in different voices for each fantasy.｣",
	"〔IN JAPAN, IT’S NOT SURPRISING IF YOU ACCIDENTALLY FIND A MANGA.〕\n\n｢In Japan, it’s common that after someone finishes a manga volume, they’ll just leave it somewhere for someone to pick it up.｣",
	"〔THE ANIME SPACE BROTHERS INCLUDES A VOICE ACTOR THAT RECORDED IN OUTER SPACE.〕\n\n｢For the 31st episode of the anime series Space Brothers, real-life astronaut Akihiko Hoshide made a guest appearance on the show and actually recorded his part aboard the International Space Station (ISS).｣",
	"〔SPIRITED AWAY WAS THE FIRST ANIME FILM TO BE NOMINATED FOR AND WIN AN ACADEMY AWARD.〕\n\n｢The Academy Award for Best Animated Feature usually doesn’t stray away from Disney and Pixar movies, but in 2003, the anime movie Spirited Away won Best Animated Feature at the 75th Academy Awards. However, Hayao Miyazaki, the director of the movie, didn’t attend the ceremony because of his opposition to the Iraq war.｣",
	"〔FIFTY NEW COLORS WERE CREATED FOR AKIRA.〕\n\n｢The critically acclaimed movie Akira was also a huge technical achievement for the Japanese anime industry. It consisted of 2,212 shots and 160,000 single pictures. This is about 2-3 times more than the average anime movie. The majority of the scenes of the film were set to take place during the night, which was generally avoided by the animators during those days because of those scenes requiring extremely high usage of colors and that too with very high precision to make the film look pleasing. Akira broke all those norms and used an astounding number of 327 colors in the movie, of which 50 were exclusively created for the film and its scene requirements.｣",
	"〔DEATH NOTE IS BANNED IN CHINA.〕\n\n｢When it comes to banning anime for inappropriate material, China certainly isn’t shy. The Chinese government has banned popular anime series like Highschool of the Dead, Attack on Titan, and Psycho-Pass without hesitation.｣",
	"〔THE CREATOR OF BLEACH HAS A REASON FOR NAMING THE ANIME BLEACH.〕\n\n｢Kubo, the creator of Bleach, stated two reasons why he named this anime as Bleach. First, because we bleach our clothes to remove stains and to whiten them, similarly to how soul reapers cleanse or bleach souls. Second, it was a Nirvana album’s name, which is one of Kubo’s favorite.｣",
	"〔THERE IS A REASON WHY EVERYONE IN CODE GEASS LOVES PIZZA.〕\n\n｢Code Geass was sponsored by Pizza Hut and also ran a massive ad campaign for them, so it was evident that pizza hut also used anime for advertising as much as possible.｣",
	"〔Anime production is insanely costly!〕\n\n｢You might've heard about this anime fact before. It (normally) costs around $100,000 to $200,000 to make a single anime episode! Then think about how much it'll actually cost to make an entire season!! ｣",
	"〔Call 'the delivery god Yato' irl〕\n\n｢The anime series Noragami featured a stray God who does odd jobs for survival. He used to leave his number everywhere so he could get customers, and guess what, they actually made it so you can call that number irl and talk to Yato! It was only available in Japan back when the anime was released. It is no longer operational now, but it was a thing back then.｣",
	"〔Anime Screams can be a good ringtone〕\n\n｢In 2015, there was a poll to choose the best ringtone, and guess what? Armin Arlet's scream, from Attack on Titan, was voted as the best ringtone ever! Imagine getting a call in a public place. Man, that'd be a laugh.｣",
	"〔Hentai - the place of new beginnings〕\n\n｢Did you know many authors and artists who made popular anime right now actually started as hentai artist? For example, the author of Food Wars was once a professional hentai artist! By the way, if you didn't know, hentai are anime porn.｣",
	"〔One Piece's ending was actually revealed!〕\n\n｢Echiro Oda, the creator of One Piece once visited a child who had cancer. The child wanted to know the ending of One Piece so badly, and so Oda told the child the entire story!｣",
	"〔Hiro Had His Personality Wiped〕\n\n｢It's a huge plot point that 002 and Hiro met as children only to have their memories wiped. Hiro didn't just get his memory changed; however, his whole personality was greatly altered to make him into a new person, as seen in the show. \nThis is because Hiro is seen as too curious and ambitious, two traits that can inspire rebellion.｣", #Darling in the Franxx Facts
	"〔Hiro Is Horrible At Art〕\n\n｢One of the many things that Hiro isn't good at is drawing. Hiro is horrible at art and has pretty much no ability to draw. This may possibly be linked to his personality rewrite, or it could just mean that Hiro is an awful artist. \nHiro likely knew this fact as he didn't really try to draw before working on his book with 002.｣",
	"〔Hiro Is Married To Ichigo In Real Life〕\n\n｢Despite 002 winning out in the anime, the real-life Hiro is married to Ichigo. The English voice actors of Ichigo and Hiro are actually married, which many fans think helped them create such a convincing performance when working together.\nThis is the closest fans will ever get to Ichigo and Hiro falling in love with each other.｣",
	"〔Hiro's Favorite Book Was The Golden Bough〕\n\n｢Hiro actually likes to read, and his favorite book is The Golden Bough. He read the book as a young child, which is surprising as it's a book about combative religion and is referenced by many people who study religion in the real world.\nHiro seems to love studying philosophy and likely would have gone on to work with human emotions if he didn't sacrifice himself.｣",
	"〔Married To Zero Two〕\n\n｢As strange as it may be, Hiro and 002 are considered to be married in the series. While there was no traditional ceremony, this happens when 002 flies through space wearing a wedding dress and announces that the two are on their honeymoon together.\nIt's nice that the series confirmed that the two got married to fans, but the way marriage works in space is pretty strange.｣",
	"〔Naming Was A Defect〕\n\n｢One of the many defects that Hiro possessed was the want to name the other parasites. This was one of the warning signs that Hiro wasn't going to work well as a parasite as it showed that he was once again too adventurous for PAPA to fully control.\nIt's a bit of a wonder why he was allowed to name any of his teammates, and his memory wasn't wiped when he began the naming process.｣",
	"〔Hiro Had The Most Partners〕\n\n｢Despite being unable to pilot at the beginning of the series, he actually has piloted the biggest assortment of franxx and rode with the most partners. While 002 is the only one he is completely compatible with, this shows that Hiro is actually pretty versatile.\nThe fact he had so much trouble piloting with others is likely due to the fact he had 002's blood in him from a young age.｣",
	"〔Different In The Manga〕\n\n｢Hiro's story in the manga is actually quite different towards the end. In the manga, 002 and Hiro don't die and go on to live a normal life with the rest of the parasites left on Earth. This is a unique take on the ending, but it doesn't really reveal much about the future of the pair.\nIf you are looking for a happier ending than what was shown in the anime, the manga is the way to go.｣",
	"〔He Rides With Mitsuru In The Manga〕\n\n｢Mitsuru and Hiro promised to ride together when they were younger, while this is never done in the anime, the manga lets this happen. This is a huge deal as same-sex pairs aren't supposed to be capable of piloting a franxx together.\nHiro did forget this promise during his memory wipe but made sure to carry through on it in the manga much to many fans delight.｣",
	"〔His Piloting Obsession Isn't Natural〕\n\n｢Hiro never had a natural obsession with piloting; it was added in place of his undesirable nature when he was altered after meeting 002. This caused Hiro to be willing to throw away his own life as he is programmed to believe that his life is useless unless he can use a franxx.\nThis is even shown up to the very end of the show, and despite his love for 002 doesn't seem to ever fully go away.｣", #DITFXX Facts end here
	"〔Konoha’s Orange Hokage Is A Reference To Naruto’s Parents〕\n\n｢Once Naruto Uzumaki became the Hokage, he referenced himself as the “Orange Hokage.” Fans might have thought that was a reference to his penchant for orange clothing early in the series. That’s not entirely the case.\nThe orange was actually a reference to his parents. Kushina, and her Uzumaki Clan, were known for their red hair. Minato, though fans don’t know much about his family, had blond hair. Red and yellow, as anyone who has taken an art class will know, make orange.｣", #Naruto Facts Start
	"〔Naruto Could Originally Turn Into A Fox〕\n\n｢Fans of the Naruto series know that the title character has the power of the nine-tailed fox Kurama inside of him. That wasn’t always the plan.\nInstead, Masashi Kishimoto wanted to write a story with a character named Naruto who was studying to be a chef. That story didn’t make it to print, but Kishimoto did keep the character name for a one-shot he created for Shonen Jump. The idea was of a young boy named Naruto who could transform into a giant fox, though his father would be the fox that rampaged and destroyed a village.｣",
	"〔Naruto Appeared On A One Piece Cover〕\n\n｢Like Naruto, One Piece has become a huge part of manga and anime history. The manga actually honored Naruto as Kishimoto’s series was coming to an end.\nThe cover of the 766th chapter of One Piece depicted two characters sharing a meal on the cover. One of those characters was hidden behind One Piece’s Nami, who also happened to be wearing clothing patterned with Konohagakure’s symbol on it. The design of the person’s clothing indicated it was Naruto himself, though it was One Piece’s Monkey D. Luffy enjoying ramen instead of Naruto.｣",
	"〔Kishimoto’s Wife Believed Naruto Would End Up With Sakura〕\n\n｢Naruto had a bit of a crush on Sakura during the early years of the series, Sakura had feelings for Sasuke, and Hinata had a crush on Naruto. Eventually, Naruto ended up married to Hinata, and their son became the focal point of the Boruto series, while Sakura and Sasuke also had a daughter. There were some fans, however, who wondered if Sakura could have ended up with Naruto. One of those fans is pretty close to Masashi Kishimoto.\nWhen he appeared at New York Comic Con in 2015, Kishimoto revealed even his wife was surprised when The Last: Naruto The Movie revealed that Naruto had fallen for Hinata. Kishimoto attempted to placate his wife by saying he modeled Hinata after her, though he actually got some of Sakura’s personality traits from his wife instead.｣",
	"〔Naruto Is One Of The Biggest Selling Manga Titles In The World〕\n\n｢When it comes to sales, Naruto is the fourth highest selling manga series of all time. It is beaten only by Dragon Ball, Golgo 13 and One Piece. This is very high praise, as Dragon Ball Z was the biggest manga series of the nineties, with One Piece taking over its place when it finished. Golgo 13 is on the list because it has been in publication since 1968! Golgo 13 is older than most of the people reading this article, and is still going strong.｣",
	"〔Naruto Has Numerous References To Dragon Ball Z〕\n\n｢Like most manga artists that work in the action/battle genre, Masashi Kishimoto was heavily inspired by Dragon Ball Z. He has stated this as fact in many interviews, as well as in the blurbs that were included in the collected Naruto volumes. This should come as no surprise, as Dragon Ball Z was a cultural phenomenon in Japan throughout the '90s.\nWhen it came to creating his own manga series, Kishimoto decided to include some references to Dragon Ball Z. The first one was a mask of Chiaotzu that was being sold at a fair. As the series went on, a much bigger reference was included, in the form of new characters that were directly inspired by Dragon Ball Z. ｣",
	"〔Kakashi used to have a slogan.〕\n\n｢During earlier drafts of Naruto, Kakashi would end his sentences with “gozaru,” a polite and old fashioned mannerism.｣",
	"〔Chouji’s dad is part of the group that wanted to kill Naruto in Chapter 1.〕\n\n｢This panel is on page 38 of chapter 1.｣",
	"〔Naruto’s favorite ramen shop “Ichiraku” exists in real life.〕\n\n｢Ichiraku is a ramen shop in Kyushu near the university that author Masashi Kishimoto graduated from.｣",
	"〔Shikamaru’s IQ is above 200.〕\n\n｢Just to put into perspective, Bill Gates is rumored to be around 170.｣",
	"〔Asuma’s cigarette is never lit in the official American version〕\n\n｢The smoke effects were specifically edited out.｣",
	"〔Naruto wasn’t supposed to be a ninja.〕\n\n｢At first, Naruto Uzumaki was supposed to be able to use a form of magic instead of ninjutsu. But the author thought this was confusing, so just made Naruto a ninja.｣",
	"〔The anime almost got cancelled.〕\n\n｢A certain organization was not happy at the high amount of deaths in the series, and issued a complaint, requesting one of the sponsors of the show to pull their funding.｣",
	"〔The Naruto BGM was chosen with overseas viewers in mind.〕\n\n｢The producers of the anime had already planned on releasing Naruto outside of Japan from the start, so they sought out music that contained a lot of Japanese instruments such as taiko, shakuhachi, and shamisen because they would be a more unfamiliar experience for non-Japanese people.｣",
	"〔The Legendary Sannin are a reference to an old novel.〕\n\n｢The trio of Jiraiya, Tsunade, and Orochimaru exist as characters from a novel named “The Ballad of the Hero Jiraiya,” published in 1839.｣",
	"〔He's A Very Emphatic Person〕\n\n｢Despite empathy being a defining trait of many male shounen protagonists, Tanjiro takes his empathy too far sometimes. While it is good to be kind to people, Tanjiro is often seen sympathizing with demons and hesitating to attack them, as a result of which he has often been taken advantage of, both emotionally and in the battlefield.｣",
	"〔His Demon Slayer Mark〕\n\n｢Upon being attacked by the Upper Moon Six demon named Gyutaro, Tanjiro's demon mark was awakened for the first time. The second time it happened when Tanjiro was battling Upper Moon three's Akaza. This mark has shown to increase his speed, strength and agility tenfold, giving him the benefit of defeating powerful monsters he would otherwise not have been able to kill.｣",
	"〔He Has Rough Hands〕\n\n｢This is a small detail that's mentioned for a few seconds in the anime, something many fans would have missed. Ever since Tanjiro decided to become a demon slayer, he had to find a master and undergo strict training. It's been noted that his master Sakonji Urokodaki's tough training resulted in Tanjiro's hands becoming rougher.｣",
	"〔Tanjiro Goes Into A Coma〕\n\n｢The anime hasn't caught up to the manga yet, so most anime fans will not know this detail. In the Swordsmith Village Arc in the manga, after a huge battle at Gyutari with Daki, Tanjiro goes into a coma.｣",
	"〔He's Banned From A Specific Hashira Training Program Activity〕\n\n｢This occurs during the Hashira Training Arc in the Demon Slayer manga. The Hashira Training Program, as the name suggests, is a program for Demon Slayers to participate in. Tanjiro manages to finish every course he participates in, save one. And that is the Wind Hashira course, who have banned him for attacking one of their own - Genya.｣"
	"〔He Looks Similar To His Ancestor〕\n\n｢Tanjiro has an ancestor named Sumiyoshi, about whom not much has been revealed. It has been explained that both these men look very similar in appearances, despite Sumiyoshi's hair is much longer and tied back in a ponytail. This yet another manga fact which was never mentioned in the anime,｣",
	"〔Muzan Is The First One To Bring Out His Inner Rage〕\n\n｢Muzan is the primary antagonist of Demon Slayer: Kimetsu no Yaiba, and the reason why demons are wreaking havoc in the human world. Tanjiro's first meeting with Muzan ends with him being confused about his identity (since he is with his human family). However, when they meet later again, Muzan manages to escape Tanjiro's grip. As a result of which, the young boy flies into a rage (something that no one knew was hidden inside him) and swears to cut off the demon's head.｣",
	"〔He Can Smell Those Who Are Underground〕\n\n｢The anime makes it clear that Tanjiro has a keen sense of smell, much like his master Sakonji Urokodaki. However, one tiny detail most fans are unaware of is that Tanjiro is able to smell what's hiding beneath layers and layers of soil. His master also claimed that the young boy had a “scent of kindness” himself and shrugged him off as someone too weak to make life and death decisions.｣",
	"〔Tanjiro's VA Was Popular For Doing Sad Roles〕\n\n｢Natsuki Hanae is a semi-popular voice actor in Japan who's most well known for voicing sad male characters. Tanjiro was his very first shounen lead, and Hanae said he had a lot of fun voicing him, especially since Tanjiro allowed him to test his vocal range and abilities a lot more than his usual crop of characters.｣",
	"〔Tanjiro Becomes A Demon〕\n\n｢After Tanjiro manages to defeat Muzan in an epic battle, Muzan transfers all his emotions into Tanjiro and turns him into a demon. Now since he has lost his humanity, Tanjiro starts blindly attacking Demon Slayers around him. However, a flashback helps him in regaining control of his human side.｣",
)
#Format: "〔〕\n\n｢｣", Change it as per your style.


PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [['⌐■', '■'], [' ͠°', ' °'], ['⇀', '↼'], ['´• ', ' •`'], ['´', '`'],
        ['`', '´'], ['ó', 'ò'], ['ò', 'ó'], ['⸌', '⸍'], ['>',
                                                         '<'], ['Ƹ̵̡', 'Ʒ'],
        ['ᗒ', 'ᗕ'], ['⟃', '⟄'], ['⪧', '⪦'], ['⪦', '⪧'], ['⪩', '⪨'], ['⪨', '⪩'],
        ['⪰', '⪯'], ['⫑', '⫒'], ['⨴', '⨵'], ['⩿', '⪀'], ['⩾', '⩽'], ['⩺', '⩹'],
        ['⩹', '⩺'], ['◥▶', '◀◤'], ['◍', '◎'], ['/͠-', '┐͡-\\'], ['⌣', '⌣”'],
        [' ͡⎚', ' ͡⎚'], ['≋'], ['૦ઁ'], ['  ͯ'], ['  ͌'], ['ළ'], ['◉'], ['☉'],
        ['・'], ['▰'], ['ᵔ'], [' ﾟ'], ['□'], ['☼'], ['*'], ['`'], ['⚆'], ['⊜'],
        ['>'], ['❍'], ['￣'], ['─'], ['✿'], ['•'], ['T'], ['^'], ['ⱺ'], ['@'],
        ['ȍ'], ['  '], ['  '], ['x'], ['-'], ['$'], ['Ȍ'], ['ʘ'], ['Ꝋ'],
        [''], ['⸟'], ['๏'], ['ⴲ'], ['◕'], ['◔'], ['✧'], ['■'], ['♥'], [' ͡°'],
        ['¬'], [' º '], ['⨶'], ['⨱'], ['⏓'], ['⏒'], ['⍜'], ['⍤'], ['ᚖ'], ['ᴗ'],
        ['ಠ'], ['σ'], ['☯']]

MOUTHS = [['v'], ['ᴥ'], ['ᗝ'], ['Ѡ'], ['ᗜ'], ['Ꮂ'], ['ᨓ'], ['ᨎ'],
          ['ヮ'], ['╭͜ʖ╮'], [' ͟ل͜'], [' ͜ʖ'], [' ͟ʖ'], [' ʖ̯'], ['ω'], [' ³'],
          [' ε '], ['﹏'], ['□'], ['ل͜'], ['‿'], ['╭╮'], ['‿‿'], ['▾'], ['‸'],
          ['Д'], ['∀'], ['!'], ['人'], ['.'], ['ロ'], ['_'], ['෴'], ['ѽ'], ['ഌ'],
          ['⏠'], ['⏏'], ['⍊'], ['⍘'], ['ツ'], ['益'], ['╭∩╮'], ['Ĺ̯'], ['◡'],
          [' ͜つ']]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = ("(╯°□°）╯彡 ┻━┻", "I ran out of tables, will order more.",
         "Go do some work instead of flippin tables.")
